import { ProductCard } from '@features/product/ui/ProductCard'
import { cn } from '@shared/util/cn'

export const ProductList = () => {
  return (
    <ul className={listCn}>
      <li>
        <ProductCard
          productId="1"
          itemKey="woodenSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="2"
          itemKey="steelSword"
          type="buy"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="3"
          itemKey="stoneSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="4"
          itemKey="woodenSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="5"
          itemKey="demonSword"
          type="buy"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="6"
          itemKey="dragonSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="7"
          itemKey="steelSword"
          type="buy"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="8"
          itemKey="stoneSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="9"
          itemKey="woodenSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
      <li>
        <ProductCard
          productId="10"
          itemKey="demonSword"
          type="buy"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </li>
    </ul>
  )
}

const listCn = cn`grid grid-cols-1 desktop:grid-cols-2 gap-4`
