import { ItemGradeBadge } from '@entities/item/ui/ItemGradeBadge'
import { ProductCard } from '@features/product/ui/ProductCard'
import { ProductTypeBadge } from '@features/product/ui/ProductTypeBadge'
import { Badge } from '@shared/ui/Badge'
import { Button } from '@shared/ui/Button'
import { FormField } from '@shared/ui/FormField'
import { Input } from '@shared/ui/Input'
import { Modal } from '@shared/ui/Modal'
import { Select } from '@shared/ui/Select'
import { Skeleton } from '@shared/ui/Skeleton'
import { useToast } from '@shared/ui/Toast'
import { ToggleGroup } from '@shared/ui/ToggleGroup'
import { Header } from '@widgets/layout/ui/Header'
import Head from 'next/head'
import { useState } from 'react'

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState(false)

  const toast = useToast()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
      <div className="flex flex-col gap-2 p-6">
        <Header />
        <Badge>구매</Badge>
        <ProductTypeBadge type="buy" />
        <ProductTypeBadge type="sell" />
        <ItemGradeBadge grade="normal" />
        <ItemGradeBadge grade="rare" />
        <ItemGradeBadge grade="epic" />
        <Skeleton className="w-10 h-10" />
        <ItemGradeBadge grade="legendary" />
        <Input />
        <FormField label="입력">
          <Input />
        </FormField>
        <Button variant="primary" onClick={() => toast.success('성공')}>
          성공
        </Button>
        <Button variant="primary" onClick={() => toast.error('실패')}>
          실패
        </Button>
        <Button variant="primary" onClick={() => toast.default('기본')}>
          기본
        </Button>
        <Button variant="secondary">버튼</Button>
        <Button variant="ghost">버튼</Button>
        <Select
          options={[
            { label: '전체', value: 'all' },
            { label: '구매', value: 'buy' },
            { label: '판매', value: 'sell' },
          ]}
          defaultValue="all"
        />
        <Button onClick={() => setIsModalOpen(true)}>모달 열기</Button>
        <Modal
          title="모달 제목"
          open={isModalOpen}
          onClose={() => setIsModalOpen(false)}
        >
          <div>모달 내용</div>
        </Modal>
        <ToggleGroup
          options={[
            { label: '전체', value: 'all' },
            { label: '구매', value: 'buy' },
            { label: '판매', value: 'sell' },
          ]}
          defaultValue="all"
        />
        <ProductCard
          productId="1"
          itemKey="woodenSword"
          type="sell"
          price={100}
          amount={2}
          createdAt={1763530721716}
        />
      </div>
    </>
  )
}
